services:
  redis:
    image: redis:7-alpine
    ports:
      - "${REDIS_PORT:-6379}:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 1s
      retries: 3
      start_period: 5s

  gateway:
    build: .
    image: magent2/gateway:local
    working_dir: /app
    init: true
    environment:
      - REDIS_URL=redis://redis:6379/0
      - BUS_STREAM_MAXLEN=${BUS_STREAM_MAXLEN:-}
      - SERVICE_NAME=gateway
      - LOG_FORMAT=json
      - LOG_LEVEL=${LOG_LEVEL:-info}
      # Optionally override module levels, e.g., "magent2.tools=warning"
      - LOG_MODULE_LEVELS=${LOG_MODULE_LEVELS:-}
    command: [ "uvicorn", "magent2.gateway.asgi:app", "--host", "0.0.0.0", "--port", "8000", "--log-level", "info", "--no-access-log", "--timeout-graceful-shutdown", "3" ]
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "${GATEWAY_PORT:-8000}:8000"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    stop_grace_period: 15s
    healthcheck:
      test: [ "CMD-SHELL", "python -c 'import http.client as h; c=h.HTTPConnection(\"localhost\",8000,timeout=3); c.request(\"GET\",\"/health\"); r=c.getresponse(); exit(0 if r.status<500 else 1)' " ]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 15s

  worker:
    build: .
    image: magent2/worker:local
    working_dir: /app
    init: true
    environment:
      - REDIS_URL=redis://redis:6379/0
      - BUS_STREAM_MAXLEN=${BUS_STREAM_MAXLEN:-}
      - AGENT_NAME=${AGENT_NAME:-DevAgent}
      - SERVICE_NAME=worker
      - LOG_FORMAT=json
      - LOG_LEVEL=${LOG_LEVEL:-info}
      # Optionally override module levels, e.g., "magent2.tools=warning"
      - LOG_MODULE_LEVELS=${LOG_MODULE_LEVELS:-}
      # Pass through API key from host environment or .env if present; empty by default in CI
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      # Ensure tools can be explicitly configured and terminal policy can allow commands
      - AGENT_TOOLS=${AGENT_TOOLS:-}
      # Only pass through TERMINAL_ALLOWED_COMMANDS if set in the host env.
      # Leaving it unset ensures the worker uses the built-in safe defaults.
      - TERMINAL_ALLOWED_COMMANDS
    depends_on:
      redis:
        condition: service_healthy
    command: [ "python", "-m", "magent2.worker" ]
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    stop_grace_period: 30s
    healthcheck:
      test: [ "CMD-SHELL", "python -c 'import socket; s=socket.socket(); s.settimeout(2); s.connect((\"redis\",6379)); s.close()' " ]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s
