name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Sync dependencies
        run: uv sync --locked

      - name: Ruff format (check)
        run: uv run ruff format --check

      - name: Ruff check
        run: uv run ruff check

      - name: Mypy
        run: uv run mypy

      - name: Pytest
        run: uv run pytest
